CREATE schema conductor;

CREATE SEQUENCE conductor.PERSON_SEQ;
CREATE SEQUENCE conductor.ACCOUNT_SEQ;
CREATE SEQUENCE conductor.TRANSACTION_SEQ;

CREATE TABLE conductor.PERSON ( 
	ID_PERSON INTEGER NOT NULL DEFAULT NEXTVAL('conductor.PERSON_SEQ'), 
    NAME_PERSON VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    BIRTH_DATE TIMESTAMP default null,
    
    CONSTRAINT ID_PERSON_PK PRIMARY KEY (ID_PERSON)
);

CREATE TABLE conductor.ACCOUNT ( 
    ID_ACCOUNT INTEGER NOT NULL DEFAULT NEXTVAL('conductor.ACCOUNT_SEQ'), 
    ID_PERSON integer NOT NULL,
    BALANCE BIGINT NOT NULL,
    LIMIT_WITHDRAWAL_DAILY BIGINT NOT NULL,
    ACCOUNT_TYPE integer NOT NULL,
    ACTIVE_FLAG BOOLEAN NOT NULL,
    CREATE_DATE TIMESTAMP default null,
    
    CONSTRAINT ID_ACCOUNT_PK PRIMARY KEY (ID_ACCOUNT),
    FOREIGN KEY (ID_PERSON) REFERENCES conductor.PERSON (ID_PERSON)
);

CREATE TABLE conductor.TRANSACTION ( 
    ID_TRANSACTION INTEGER NOT NULL DEFAULT NEXTVAL('conductor.TRANSACTION_SEQ'), 
    ID_ACCOUNT integer NOT NULL,
    VALUE BIGINT NOT NULL,
    TRANSACTION_DATE TIMESTAMP default null,
    
    CONSTRAINT ID_TRANSACTION_PK PRIMARY KEY (ID_TRANSACTION),
    FOREIGN KEY (ID_ACCOUNT) REFERENCES conductor.ACCOUNT (ID_ACCOUNT)
);

INSERT INTO conductor.person
(name_person, cpf, birth_date)
VALUES('Vinicius Braz Pereira', '72533915602', '04/02/1985');
